src/funcs.c
src/iGameMain.c

Can now detect the executable filename, regardless if it was started from the CLI or the Workbench. Removed hard-coded reference to PROGDIR:iGame when searching for the icon file (to read the Tooltypes)

Fixed #35: Can now detect and use the executable's filename

---

src/funcs.c
src/iGameStrings_cat.c

Make it easy for users to see which games haven't been categorized into any genre by adding "Unknown" to the bottom of the genres list.
Closes #77

Show "Unknown" genre in genres list

---

.gitignore
.vscode/c_cpp_properties.json
.vscode/settings.json
Makefile
Makefile.Windows.mak
Makefile.amigaos
Makefile.docker
Makefile.linux
src/funcs.c
src/iGameGUI.c
src/iGameMain.c

This pull request fixes a few problems, and makes iGame to compile for AmigaOS 4 native with OS4 53.30 SDK and MUI 5.0 2019R4 SDK. There are some overrides on obsolete functions that should be addressed in the future, and openings of libraries, like MuimasterFace, that should be done manually. Also, there are some libraries closings and checks. This needs to be applied to more libraries, so to provide more info to the users.
A screenshot of iGame running under AmigaOS 4 natively

Native compiling for OS4 with MUI5 and OS4 SDK

---

src/funcs.c
src/iGameGUI.c

This change keeps the proper aspect ratio for screenshots/icons displayed in the sidebar, without stretching outside of the set image bounds in settings. There's no change for when Guigfx is disabled, since in that situation the native size of the screenshot/icon image is used anyway.
The image is simply boxed within the frame due to GuigfxObject getting a fixed height and width. I tried using MUIA_MaxHeight and MUI_MaxWidth but it turned out to squeeze and shrink the image instead.
Fixes #72

Keep image aspect for screenshot/icon when Guigfx is used

---

src/funcs.c
src/iGameMain.c

Added checks and error messages for all the required libraries and minimum versions on some of them. Also, there was a serious bug fixed when someone tried to run iGame without having MUI installed. This bug crashed the whole system.
Also, the libraries are checked based on the configuration, as well. So, if the user has NOGUIGFX enabled, it will not check for GuiGfx libraries.

Added checks and error messages for all the required libraries

---

src/funcs.c

Silence a compile warning from vbcc by explicitly casting the const out when passing a game's drawer path to OpenWorkbenchObject.
Fixes #89

Pass path_only as a non-const char pointer

---

Makefile
Makefile.Windows.mak
Makefile.amigaos
Makefile.docker
Makefile.linux
helper_tools/update_titles.c
src/funcs.c
src/strcasestr.c

This takes care of the case-sensitivity issue for slave and icon filenames in (originally mentioned in https://github.com/MrZammler/iGame/issues/74#issuecomment-680142638) that leads to slaves added via "Add non-WHDLoad Game" in the menu not getting their icon recognized for image and tooltypes. I've added a case-insensitive `strstr()` implementation (named here `strcasestr()` to match with the name of a similar function from GCC's C library) and use it wherever `strstr()` has been used to check for a .slave or .info extension on files before.
One instance of `strstr()` has not been updated to use `strcasestr()` to check if the file is a slave, due to the fact that we have already lower-cased the filename beforehand:
https://github.com/MrZammler/iGame/blob/fe9949edb75a711d1baab576d2492f2f9 …

Check slave and info file names without case sensitivity

---

.gitignore
Makefile
Makefile.Windows.mak
Makefile.amigaos
Makefile.docker
Makefile.linux

Related to #92, this brings all the makefiles more or less in line with each other. Most of the differences between the makefiles have been removed, and most of what remains are platform or compiler specific.

Bring makefiles in line with each other

---

CHANGELOG.md
catalogs/italiano/iGame.ct
src/iGameGUI.c

Refactored a little bit the version string that is used in the About window, and created a new variable, called **version_string** which is used at the WB screen title
fixes #130

issue-130: Show release version in wb titlebar

---

CHANGELOG.md
src/funcs.c

For this fix added the tooltypes' first characters to the ignore list, as well as a few more that might be found in games' icons.
Fixes #139

issue-139: Wrong tooltypes in Games prevent running

---

src/iGameGUI.c

Rewrote the version and about text using snprintf, and fixed the bug on OS4 with the previous implementation.
fixes #130

issue-130: Show release version in wb titlebar (fix)

---

CHANGELOG.md
src/fsfuncs.c
src/fsfuncs.h
src/funcs.c
src/funcs.h
src/iGameExtern.h
src/iGameGUI.c
src/iGameGUI.h
src/strfuncs.c
src/strfuncs.h

In this PR:
- I made some fixes on funcs.c which were not synced right after the previous PRs
- Fixed the #162 where I check if a screenshot is supported by the installed Datatypes. If not, the image is skipped, moving to the next check. This fixes the situation where a user doesn't have Info datatype installed and an empty screenshot is shown. Now it skips that and moves to show the default image from iGame folder.
- Added a check if the screenshot is already visible. In that case it doesn't show that image again. This helps in situations where always the default image is shown because of lack of screenshots.

Issue 162 fixes

---

.vscode/settings.json
Makefile
Makefile.Windows.mak
Makefile.amigaos
Makefile.docker
Makefile.linux
make_includes/catalogs.inc

The change to iGame_strings.h from iGame_cat.c and iGame_cat.h was made only in the Docker makefile. This brings the other makefiles into sync by moving as much of the catalog rules into a shared include file as possible. Unfortunately we can't be sure that the shell OR operator is present or functional on Windows or Amiga OS, so the rule to build the actual catalog files themselves still has to be declared in each makefile individually.
This also updates VS Code config to treat the .inc files as makefiles so that proper syntax functionality is present in that editor.

Resync makefiles

---

CHANGELOG.md
Makefile.docker
src/iGameGUI.c
src/version.h

Change the versioning of iGame to follow the Semantic versioning. No more beta versions will be released. The version will have 3 digits which will be MAJOR.MINOR.PATCH. Minor versions will be increased when new features are released. When a release will have mainly fixes there is going to be a change at the PATCH digit.
More info about Semantic Versioning https://semver.org/

Introducing Semantic versioning

---

.drone.yml
Makefile.docker
make_includes/obj_000.inc
make_includes/obj_040.inc
make_includes/obj_060.inc
make_includes/obj_mos.inc
make_includes/obj_os4.inc

Enhanced the makefile for docker, removing duplicated code and and making more flexible. Now this makefile doesn't use the include files under "make_includes" folder, except the one for the catalogs. Those files remain there though so that can be used by the rest of Makefiles.
Now, in the Makefile.docker, there is only one rule for building iGame and the CPU is set by default to 000, which is for 68000. If the user wants to compile a different version the CPU argument needs to be provided, i.e
```
make -f Makefile.docker CPU=030
make -f Makefile.docker CPU=OS4
```

Enhance Makefile.docker removing duplicated code

---

CHANGELOG.md
Makefile.docker

With the previous changes of v2.2.0 there was a missing flag in compilation

Fixed 68K cpu specific versions

---

CHANGELOG.md
src/funcs.c

Willem Drijver contributed with a fix on Execute tooltype, which was not working well.
PR at https://github.com/walkero-gr/iGame/pull/39

Execute tooltype

---

required_files/Install-iGame

Fixed an installer issue when copying the icons files because the path changed. This was introduced with v2.3.0

Fixed an issue on v2.3.0 release with Icons copy

---

CHANGELOG.md
src/funcs.c

Fixed a bug on repo removal, which remained in the repos list and was included in scans, unless the user restarted iGame

Fixed repo removal from the repos list

---

CHANGELOG.md
Makefile.docker
required_files/iGame.guide
src/fsfuncs.c
src/fsfuncs.h
src/funcs.c
src/genresList.c
src/genresList.h
src/iGameExtern.h

- Now the Genre list is populated from the igame.data files and the genre file, if it exists, although it is not necessary. The genre filtering is working with these new values
- Fixed a hit when the entry properties are requested without having a selected entry

Added genres from igame.data files and a fix

---

CHANGELOG.md
src/funcs.c
src/iGameExtern.h
src/iGameGUI.c

- When realtime filtering is enabled at least 3 characters are required so as to be initiated. Less than 3 characters are ignored, unless the filtering by pressing the enter button is enabled.

Realtime filtering is enabled at least 3 characters are required

---

CHANGELOG.md
required_files/iGame.guide
src/funcs.c
src/iGameGUI.c
src/iGameGUI.h

With this PR I moved the filter options from the Genre list to a new cycle box above the entries list. Now the user can make a selection of a specific genre and Last played or Favourites. So, the results can be a combination of the show filter and the genre and of course the title.

Added a new filter cycle box above entries list

---

CHANGELOG.md
Makefile.docker
catalogs/iGame.cd
required_files/iGame.guide
src/chipsetList.c
src/chipsetList.h
src/fsfuncs.c
src/funcs.c
src/funcs.h
src/iGameExtern.h
src/iGameGUI.c
src/iGameGUI.h

With the PR I added a new cycle box above the Genre that has the chipset based on the information that is stored in the igame.data files. This way users can filter the items based on if it is an RTG, AGA or OCS/ECS etc.

Chipset filter

---

CHANGELOG.md
src/fsfuncs.c
src/funcs.c

With these changes I fixed the renaming of an item from the properties window
Also, made a few fixes on single item addition from the "Add game" window. This is initiated from the "Add game..." menu item

Fixes on renaming and single item addition

---

CHANGELOG.md
src/funcs.c
src/strfuncs.c

Some users have an issue on opening the properties of an item, which is not working for them since v2.4.1
This PR is for fixing that

Fixed the opening of the properties window for some users

---

src/iGameGUI.c

With this PR I changed the way we define hooks, using SDI. This simplifies the code by reducing duplications
Also, removed commented code that had to do with the old list.

Use SDI to define the hooks

---

CHANGELOG.md
src/funcs.c
src/iGameExtern.h

This PR is about fixing #215  
Also, if the user scans the repositories and then change the way of discovering the titles from the settings, and the rescans, the titles are changed, except those that were renamed manually from the item properties window

Fixing the issue 215 and make the scan better on changes

---

CHANGELOG.md
src/WinInfo.c
src/fsfuncs.c
src/funcs.c
src/iGameGUI.c
src/iGameMain.c

- Added the "Open game folder" menu in the MorphOS version, that was missing
- Disabled the gamepad usage on MorphOS because it was reported giving problems while playing a game
- Fixed starting WHDLoad games in MorphOS using WHDLoadopener

Morphos fixes

---

CHANGELOG.md
required_files/iGame.guide
src/WinInfo.c
src/funcs.c
src/genresList.c
src/genresList.h
src/iGameGUI.c
src/iGameGUI.h

With these PR I changed a lot the logic of Genre loading and selection
- By changing the Genre select box to a PopupString, it is now possible to edit the Genre title and create new ones, which will be added to the Genre lists
- The genres in the Information window changed to a PopupString. Now, it takes less space to choose a genre, making it possible even on small resolutions.
- The genres lists have the titles sorted alphabetically
- Removed some not necessary fill ups of genre cycle boxes and loops. This should make iGame start a little bit faster
- Removed some extra change notifications in Genres lists, which should avoid not necessary refreshes of the games/demos lists
- The genres lists were not populated when the right sidebar was disabled (#260)

Genres lists enhancements
